// the name property needs to match the name in the database
export const formFields = [
  {
    label: 'Route name',
    inputProps: { required: true, type: 'text' },
    name: 'name',
  },
  {
    label: 'Date climbed',
    inputProps: { type: 'date', min: '1900-01-01' },
    name: 'dateClimbed',
  },
  {
    label: 'YDS grade',
    inputProps: { required: true },
    name: 'grade',
    datalist: [
      '5.0',
      '5.1',
      '5.2',
      '5.3',
      '5.4',
      '5.5',
      '5.6',
      '5.7',
      '5.8-',
      '5.8',
      '5.8+',
      '5.9-',
      '5.9',
      '5.9+',
      '5.10a',
      '5.10b',
      '5.10c',
      '5.10d',
      '5.10-',
      '5.10',
      '5.10+',
      '5.11a',
      '5.11b',
      '5.11c',
      '5.11d',
      '5.11-',
      '5.11',
      '5.11+',
      '5.12a',
      '5.12b',
      '5.12c',
      '5.12d',
      '5.12-',
      '5.12',
      '5.12+',
      '5.13a',
      '5.13b',
      '5.13c',
      '5.13d',
      '5.13-',
      '5.13',
      '5.13+',
      '5.14a',
      '5.14b',
      '5.14c',
      '5.14d',
      '5.14-',
      '5.14',
      '5.14+',
      '5.15a',
      '5.15b',
      '5.15c',
      '5.15d',
      '5.15-',
      '5.15',
      '5.15+',
    ],
  },
  {
    label: 'Type',
    inputProps: { type: 'text' },
    name: 'type',
  },
  {
    label: 'Length',
    inputProps: { type: 'text' },
    name: 'length',
  },
  {
    label: 'Pitches',
    inputProps: { type: 'number' },
    name: 'pitches',
  },
  {
    label: 'Grade',
    inputProps: { type: 'text' },
    name: 'commitmentGrade',
  },
  {
    label: 'Description',
    inputProps: {
      type: 'textarea',
      placeholder: 'What do you have to say about the route?',
    },
    name: 'description',
  },
  {
    label: 'Gear',
    inputProps: {
      type: 'textarea',
      placeholder:
        'Add some gear here, unless you free soloed. What kind of shoes did you wear?',
    },
    name: 'gear',
  },
  {
    label: 'Cover image URL',
    inputProps: { type: 'text' },
    name: 'imageCoverUrl',
  },
];
